/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mediseek.pat.Receptionist;

/**
 *
 * @author tendi
 */
public class addAppointmentGUI extends javax.swing.JFrame {

    /**
     * Creates new form addAppointmentGUI
     */
    public addAppointmentGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        lblTitle = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        tf_Symptoms = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jCheckBox1 = new javax.swing.JCheckBox();
        jLabel10 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        tf_PatientID = new javax.swing.JTextField();
        tf_StaffID = new javax.swing.JTextField();
        BTNSchedule = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 102, 102));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jDateChooser1.setBackground(new java.awt.Color(9, 39, 39));
        jPanel1.add(jDateChooser1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 310, 380, -1));

        lblTitle.setFont(new java.awt.Font("Bookman Old Style", 1, 36)); // NOI18N
        lblTitle.setForeground(new java.awt.Color(102, 255, 204));
        lblTitle.setText("New Appointment:");
        jPanel1.add(lblTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, 370, 80));

        jLabel7.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jLabel7.setText("Staff ID of Specialist:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, 150, 30));

        tf_Symptoms.setBackground(new java.awt.Color(6, 23, 37));
        tf_Symptoms.setForeground(new java.awt.Color(255, 255, 255));
        tf_Symptoms.setToolTipText("Enter the ID of the patient you wish to schedule an appointment for. NOTE: They have to be added as a patient in the hospital database or you may not progress!!");
        jPanel1.add(tf_Symptoms, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 480, 340, 50));

        jLabel8.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jLabel8.setText("Symptoms Experienced:");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 450, 180, 30));

        jLabel9.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jLabel9.setText("Patient ID:");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 150, 90, 30));

        jCheckBox1.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        jCheckBox1.setText("Will they be admitted to the hospital?");
        jPanel1.add(jCheckBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 530, 280, 30));

        jLabel10.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jLabel10.setText("Date of Appointment:");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 270, 160, 30));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "08:00", "08:30", "09:00", "09:30", "10:00", "10:30", "11:00", "11:30", "12:00", "12:30", "13:00", "13:30", "14:00", "14:30", "15:00", "15:30", "16:00", "16:30", "17:00", "17:30", "18:00" }));
        jPanel1.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 400, 80, -1));

        jLabel11.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jLabel11.setText("Time of Appointment:");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 360, 160, 30));

        tf_PatientID.setBackground(new java.awt.Color(6, 23, 37));
        tf_PatientID.setForeground(new java.awt.Color(255, 255, 255));
        tf_PatientID.setToolTipText("Enter the ID of the patient you wish to schedule an appointment for. NOTE: They have to be added as a patient in the hospital database or you may not progress!!");
        jPanel1.add(tf_PatientID, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 150, 180, 40));

        tf_StaffID.setBackground(new java.awt.Color(6, 23, 37));
        tf_StaffID.setForeground(new java.awt.Color(255, 255, 255));
        tf_StaffID.setToolTipText("Enter the ID of the patient you wish to schedule an appointment for. NOTE: They have to be added as a patient in the hospital database or you may not progress!!");
        jPanel1.add(tf_StaffID, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 210, 180, 40));

        BTNSchedule.setBackground(new java.awt.Color(0, 204, 51));
        BTNSchedule.setForeground(new java.awt.Color(0, 0, 0));
        BTNSchedule.setText("SCHEDULE");
        BTNSchedule.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNScheduleActionPerformed(evt);
            }
        });
        jPanel1.add(BTNSchedule, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 570, -1, -1));

        jButton3.setBackground(new java.awt.Color(102, 102, 102));
        jButton3.setText("CLOSE");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 570, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 420, 610));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BTNScheduleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNScheduleActionPerformed
        // Add Appointment to the database
        
        
    }//GEN-LAST:event_BTNScheduleActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed

        this.dispose();

    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(addAppointmentGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(addAppointmentGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(addAppointmentGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(addAppointmentGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new addAppointmentGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BTNSchedule;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JComboBox<String> jComboBox1;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JTextField tf_PatientID;
    private javax.swing.JTextField tf_StaffID;
    private javax.swing.JTextField tf_Symptoms;
    // End of variables declaration//GEN-END:variables
}
