/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mediseek.pat.Receptionist;

import javax.swing.DefaultListModel;
import mediseek.pat.START.LoginGUIoption;
import mediseek.pat.Staff;
import mediseek.pat.useStaff;

/**
 *
 * @author tendi
 */
public class ReceptionistPage extends javax.swing.JFrame {

    /**
     * Creates new form PharmacistPage
     */
    public ReceptionistPage() {
        initComponents();
    }
    
    
    
 DefaultListModel dlstStaff = new DefaultListModel();
 Staff[] staffDirectory = new Staff[500]; 
 useStaff objStaff = new useStaff();

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        ViewPatientsTab = new javax.swing.JScrollPane();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        lstPatients = new javax.swing.JList<>();
        tf_sName = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        lblTitle1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btnAddPatientPage = new javax.swing.JButton();
        btnShowPatient1 = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        tf_fName1 = new javax.swing.JTextField();
        lblTitle7 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnAddApp1 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        lblTitle8 = new javax.swing.JLabel();
        PatientInfoPanel = new javax.swing.JPanel();
        tfname = new javax.swing.JTextField();
        lblname2 = new javax.swing.JLabel();
        lblsname2 = new javax.swing.JLabel();
        tfDiagnosis2 = new javax.swing.JTextField();
        lblgender3 = new javax.swing.JLabel();
        tfSname = new javax.swing.JTextField();
        lbldIAGNOSIS2 = new javax.swing.JLabel();
        tfSymptoms = new javax.swing.JTextField();
        lblSymptoms2 = new javax.swing.JLabel();
        jCheckBox1 = new javax.swing.JCheckBox();
        cbSpecCode = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        lblgender2 = new javax.swing.JLabel();
        jComboBox3 = new javax.swing.JComboBox<>();
        jTextField2 = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        ViewStaffTab1 = new javax.swing.JPanel();
        PatientInfoPanel3 = new javax.swing.JPanel();
        tfPassword1 = new javax.swing.JTextField();
        lblname6 = new javax.swing.JLabel();
        lblsname5 = new javax.swing.JLabel();
        tfQual1 = new javax.swing.JTextField();
        lblJD2 = new javax.swing.JLabel();
        tfSname3 = new javax.swing.JTextField();
        lbldIAGNOSIS5 = new javax.swing.JLabel();
        tfResidence1 = new javax.swing.JTextField();
        lblSymptoms5 = new javax.swing.JLabel();
        cbGender1 = new javax.swing.JComboBox<>();
        jLabel27 = new javax.swing.JLabel();
        btnLOGOUT1 = new javax.swing.JButton();
        cbSpecialty1 = new javax.swing.JComboBox<>();
        lblgender5 = new javax.swing.JLabel();
        lblJD3 = new javax.swing.JLabel();
        cbJob2 = new javax.swing.JComboBox<>();
        tfname4 = new javax.swing.JTextField();
        jLabel28 = new javax.swing.JLabel();
        lblname7 = new javax.swing.JLabel();
        lblname11 = new javax.swing.JLabel();
        tfContact1 = new javax.swing.JTextField();
        tfStaffID1 = new javax.swing.JTextField();
        jLabel29 = new javax.swing.JLabel();
        jScrollPane6 = new javax.swing.JScrollPane();
        lstStaff1 = new javax.swing.JList<>();
        jComboBox5 = new javax.swing.JComboBox<>();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        lblTitle9 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        cbSpecialtyOrder1 = new javax.swing.JComboBox<>();
        ViewAppointmentsTab = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        lstAppoint = new javax.swing.JList<>();
        lblTitle2 = new javax.swing.JLabel();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        btnAddApp = new javax.swing.JButton();
        AddPatientTab = new javax.swing.JPanel();
        tfnameADDp = new javax.swing.JTextField();
        lblname = new javax.swing.JLabel();
        lblsname = new javax.swing.JLabel();
        tfDiagnosis = new javax.swing.JTextField();
        lblgender1 = new javax.swing.JLabel();
        tfSnameADDp = new javax.swing.JTextField();
        lbldIAGNOSIS = new javax.swing.JLabel();
        tfSymptomsADDp = new javax.swing.JTextField();
        lblSymptoms = new javax.swing.JLabel();
        cbMedAidADDp = new javax.swing.JCheckBox();
        cbGenderADDp = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        btnAddPatient = new javax.swing.JButton();
        lblTitle6 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        ViewPatientsHistoryTab = new javax.swing.JPanel();
        lblTitle3 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jButton1 = new javax.swing.JButton();
        AddStaffTab = new javax.swing.JPanel();
        tfPasswordADD1 = new javax.swing.JTextField();
        lblname8 = new javax.swing.JLabel();
        lblsname4 = new javax.swing.JLabel();
        tfQualADD1 = new javax.swing.JTextField();
        lblJD4 = new javax.swing.JLabel();
        tfSnameADD1 = new javax.swing.JTextField();
        lbldIAGNOSIS4 = new javax.swing.JLabel();
        tfResidenceADD1 = new javax.swing.JTextField();
        lblSymptoms4 = new javax.swing.JLabel();
        cbGenderADD1 = new javax.swing.JComboBox<>();
        jLabel14 = new javax.swing.JLabel();
        btnAddStaff1 = new javax.swing.JButton();
        btnLOGOUT2 = new javax.swing.JButton();
        cbSpecialtyADD1 = new javax.swing.JComboBox<>();
        lblgender6 = new javax.swing.JLabel();
        lblJD5 = new javax.swing.JLabel();
        cbJobADD1 = new javax.swing.JComboBox<>();
        tfnameADD1 = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        lblname9 = new javax.swing.JLabel();
        lblname10 = new javax.swing.JLabel();
        tfContactADD1 = new javax.swing.JTextField();
        lblTitle4 = new javax.swing.JLabel();
        btnLogout = new javax.swing.JButton();
        lblTitle = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar3 = new javax.swing.JMenuBar();
        jMenu5 = new javax.swing.JMenu();
        jMenu6 = new javax.swing.JMenu();

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        jMenu3.setText("File");
        jMenuBar2.add(jMenu3);

        jMenu4.setText("Edit");
        jMenuBar2.add(jMenu4);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setBackground(new java.awt.Color(126, 145, 158));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jScrollPane1.setViewportView(lstPatients);

        jPanel4.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 200, 1030, 220));
        jPanel4.add(tf_sName, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 100, 150, -1));

        jLabel3.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jLabel3.setText("Patient Information:");
        jPanel4.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 440, 140, 30));

        lblTitle1.setFont(new java.awt.Font("Bookman Old Style", 1, 12)); // NOI18N
        lblTitle1.setForeground(new java.awt.Color(255, 255, 255));
        lblTitle1.setText("*If Patient cannot be found in the Database:");
        jPanel4.add(lblTitle1, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 10, 310, 80));

        jLabel4.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jLabel4.setText("Patient Surname:");
        jPanel4.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 100, 130, 30));

        btnAddPatientPage.setText("Add a new Patient");
        btnAddPatientPage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddPatientPageActionPerformed(evt);
            }
        });
        jPanel4.add(btnAddPatientPage, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 70, 150, -1));

        btnShowPatient1.setText("Search Patient by Names");
        btnShowPatient1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnShowPatient1ActionPerformed(evt);
            }
        });
        jPanel4.add(btnShowPatient1, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 140, 180, -1));

        jLabel16.setText("Name");
        jPanel4.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 180, -1, -1));

        jLabel17.setText("Surname");
        jPanel4.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 180, -1, -1));

        jLabel12.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jLabel12.setText("Patient First Name:");
        jPanel4.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 70, 160, 30));
        jPanel4.add(tf_fName1, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 70, 150, -1));

        lblTitle7.setFont(new java.awt.Font("Bookman Old Style", 1, 25)); // NOI18N
        lblTitle7.setForeground(new java.awt.Color(255, 255, 255));
        lblTitle7.setText("View Patients:");
        jPanel4.add(lblTitle7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 0, 310, 80));

        jLabel2.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        jLabel2.setText("Step 2)");
        jPanel4.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 100, -1, 50));

        btnAddApp1.setText("Add new Appointment");
        btnAddApp1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddApp1ActionPerformed(evt);
            }
        });
        jPanel4.add(btnAddApp1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 110, 150, -1));

        jLabel7.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        jLabel7.setText("Step 1)");
        jPanel4.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 70, -1, 30));

        lblTitle8.setFont(new java.awt.Font("Bookman Old Style", 1, 25)); // NOI18N
        lblTitle8.setForeground(new java.awt.Color(255, 255, 255));
        lblTitle8.setText("OR:");
        jPanel4.add(lblTitle8, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 60, 70, 80));

        PatientInfoPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tfname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfnameActionPerformed(evt);
            }
        });
        PatientInfoPanel.add(tfname, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 90, 230, 50));

        lblname2.setText("Name:");
        PatientInfoPanel.add(lblname2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 90, 90, 30));

        lblsname2.setText("Surname:");
        PatientInfoPanel.add(lblsname2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 160, 90, -1));

        tfDiagnosis2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfDiagnosis2ActionPerformed(evt);
            }
        });
        PatientInfoPanel.add(tfDiagnosis2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 360, 430, 60));

        lblgender3.setText("Specialty Code:");
        PatientInfoPanel.add(lblgender3, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 270, 90, 30));

        tfSname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfSnameActionPerformed(evt);
            }
        });
        PatientInfoPanel.add(tfSname, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 160, 230, 50));

        lbldIAGNOSIS2.setText("Diagnosis:");
        PatientInfoPanel.add(lbldIAGNOSIS2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 370, 90, 30));

        tfSymptoms.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfSymptomsActionPerformed(evt);
            }
        });
        PatientInfoPanel.add(tfSymptoms, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 500, 430, 70));

        lblSymptoms2.setText("Prescription:");
        PatientInfoPanel.add(lblSymptoms2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 490, 90, 30));

        jCheckBox1.setText("Patient Possesses Medical Aid");
        jCheckBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox1ActionPerformed(evt);
            }
        });
        PatientInfoPanel.add(jCheckBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 320, 210, -1));

        cbSpecCode.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Male", "Female" }));
        cbSpecCode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbSpecCodeActionPerformed(evt);
            }
        });
        PatientInfoPanel.add(cbSpecCode, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 270, 120, 30));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mediseek/pat/Doctor/INJUREDpatient.png"))); // NOI18N
        PatientInfoPanel.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 70, 280, 280));

        jButton2.setText("Update Patient Details");
        PatientInfoPanel.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 540, 160, -1));

        lblgender2.setText("Sex:");
        PatientInfoPanel.add(lblgender2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 270, 90, 30));

        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Male", "Female" }));
        jComboBox3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox3ActionPerformed(evt);
            }
        });
        PatientInfoPanel.add(jComboBox3, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 270, 120, 30));
        PatientInfoPanel.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 30, 180, -1));

        jLabel25.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jLabel25.setText("Patient ID:");
        PatientInfoPanel.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 30, 90, 30));

        jPanel4.add(PatientInfoPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 470, 1070, 580));

        ViewPatientsTab.setViewportView(jPanel4);

        jTabbedPane1.addTab("View Patients", ViewPatientsTab);

        ViewStaffTab1.setBackground(new java.awt.Color(126, 145, 158));
        ViewStaffTab1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        PatientInfoPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tfPassword1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfPassword1ActionPerformed(evt);
            }
        });
        PatientInfoPanel3.add(tfPassword1, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 430, 170, 30));

        lblname6.setText("Staff ID Password: ");
        PatientInfoPanel3.add(lblname6, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 430, 120, 30));

        lblsname5.setText("Surname:");
        PatientInfoPanel3.add(lblsname5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 160, 90, -1));

        tfQual1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfQual1ActionPerformed(evt);
            }
        });
        PatientInfoPanel3.add(tfQual1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 490, 430, 70));

        lblJD2.setText("Specialty: ");
        PatientInfoPanel3.add(lblJD2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 320, 90, 30));

        tfSname3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfSname3ActionPerformed(evt);
            }
        });
        PatientInfoPanel3.add(tfSname3, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 160, 230, 50));

        lbldIAGNOSIS5.setText("Qualifications:");
        PatientInfoPanel3.add(lbldIAGNOSIS5, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 490, 90, 30));

        tfResidence1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfResidence1ActionPerformed(evt);
            }
        });
        PatientInfoPanel3.add(tfResidence1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 400, 430, 60));

        lblSymptoms5.setText("Residence:");
        PatientInfoPanel3.add(lblSymptoms5, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 400, 90, 30));

        cbGender1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Male", "Female" }));
        cbGender1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbGender1ActionPerformed(evt);
            }
        });
        PatientInfoPanel3.add(cbGender1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 230, 200, 30));

        jLabel27.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mediseek/pat/Doctor/medicalstafficon.jpg"))); // NOI18N
        PatientInfoPanel3.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 70, 260, 270));

        btnLOGOUT1.setText("LOGOUT");
        btnLOGOUT1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLOGOUT1ActionPerformed(evt);
            }
        });
        PatientInfoPanel3.add(btnLOGOUT1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1090, -440, -1, -1));

        cbSpecialty1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select a specialty:", "Administration", "General Practitioner", "Cardiologist", "Pharmacist", "Infectious Diseases Specialist", "Prosthetist", "Neurologist", "Gynaecologist", "Oncologist", " ", " " }));
        PatientInfoPanel3.add(cbSpecialty1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 320, 200, 30));

        lblgender5.setText("Sex:");
        PatientInfoPanel3.add(lblgender5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 230, 90, 30));

        lblJD3.setText("Job Description:");
        PatientInfoPanel3.add(lblJD3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 270, 90, 30));

        cbJob2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select a description", "Doctor", "Pharmacist", "Receptionist", "Administrator" }));
        PatientInfoPanel3.add(cbJob2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 270, 200, 30));

        tfname4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfname4ActionPerformed(evt);
            }
        });
        PatientInfoPanel3.add(tfname4, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 90, 230, 50));

        jLabel28.setText("Personal Information");
        PatientInfoPanel3.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 350, 130, 30));

        lblname7.setText("Name:");
        PatientInfoPanel3.add(lblname7, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 90, 90, 30));

        lblname11.setText("Contact No:");
        PatientInfoPanel3.add(lblname11, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 390, 90, 30));

        tfContact1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfContact1ActionPerformed(evt);
            }
        });
        PatientInfoPanel3.add(tfContact1, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 390, 170, 30));

        tfStaffID1.setToolTipText("Enter the Staff ID of the meber you wish to search and proceed to click the Search Patient Button below");
        tfStaffID1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfStaffID1ActionPerformed(evt);
            }
        });
        PatientInfoPanel3.add(tfStaffID1, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 30, 180, -1));

        jLabel29.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jLabel29.setText("Staff ID:");
        PatientInfoPanel3.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 30, 90, 30));

        ViewStaffTab1.add(PatientInfoPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 340, 1070, 600));

        lstStaff1.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        lstStaff1.setModel(dlstStaff);
        jScrollPane6.setViewportView(lstStaff1);

        ViewStaffTab1.add(jScrollPane6, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 110, 900, 130));

        jComboBox5.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "No Order", "Alphabetical Order (First Name)", "Alphabetical Order (First Name)", "Gender", "Job Description", "Specialty" }));
        ViewStaffTab1.add(jComboBox5, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 270, 220, -1));

        jLabel30.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jLabel30.setText("Search Staff by Specialty:");
        ViewStaffTab1.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, 260, 30));

        jLabel31.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jLabel31.setText("Staff Information:");
        ViewStaffTab1.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 300, 140, 30));

        lblTitle9.setFont(new java.awt.Font("Bookman Old Style", 1, 25)); // NOI18N
        lblTitle9.setForeground(new java.awt.Color(255, 255, 255));
        lblTitle9.setText("View Staff");
        ViewStaffTab1.add(lblTitle9, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, 310, 80));

        jLabel32.setText("Name");
        ViewStaffTab1.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 90, -1, -1));

        jLabel33.setText("Surname");
        ViewStaffTab1.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 90, -1, -1));

        jLabel34.setText("Staff ID");
        ViewStaffTab1.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 90, -1, -1));

        jLabel35.setText("Specialty");
        ViewStaffTab1.add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 90, -1, -1));

        jLabel36.setText("Sex");
        ViewStaffTab1.add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 90, -1, -1));

        jLabel37.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jLabel37.setText("Place Staff in order of:");
        ViewStaffTab1.add(jLabel37, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 270, 220, 30));

        cbSpecialtyOrder1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "NONE", "Biokinetics", "Cardiologist", "Gynaecologist", "General Practitioner", "Infectious Diseases Specialist", "Neurologist", "Oncologist", "Pharmacist", "Prosthetist", "Psychologist", "Radiologist" }));
        cbSpecialtyOrder1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbSpecialtyOrder1ActionPerformed(evt);
            }
        });
        ViewStaffTab1.add(cbSpecialtyOrder1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 160, 160, -1));

        jScrollPane5.setViewportView(ViewStaffTab1);

        jTabbedPane1.addTab("View Staff", jScrollPane5);

        ViewAppointmentsTab.setBackground(new java.awt.Color(126, 145, 158));
        ViewAppointmentsTab.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jScrollPane2.setViewportView(lstAppoint);

        ViewAppointmentsTab.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, 1180, 460));

        lblTitle2.setFont(new java.awt.Font("Bookman Old Style", 1, 25)); // NOI18N
        lblTitle2.setForeground(new java.awt.Color(255, 255, 255));
        lblTitle2.setText("View Appointments:");
        ViewAppointmentsTab.add(lblTitle2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 310, 80));
        ViewAppointmentsTab.add(jDateChooser1, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 60, 290, -1));

        btnAddApp.setText("Add new Appointment");
        btnAddApp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddAppActionPerformed(evt);
            }
        });
        ViewAppointmentsTab.add(btnAddApp, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 570, 150, -1));

        jTabbedPane1.addTab("View Appointments", ViewAppointmentsTab);

        AddPatientTab.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tfnameADDp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfnameADDpActionPerformed(evt);
            }
        });
        AddPatientTab.add(tfnameADDp, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 90, 230, 50));

        lblname.setText("Name:");
        AddPatientTab.add(lblname, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 90, 90, 30));

        lblsname.setText("Surname:");
        AddPatientTab.add(lblsname, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 160, 90, -1));

        tfDiagnosis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfDiagnosisActionPerformed(evt);
            }
        });
        AddPatientTab.add(tfDiagnosis, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 510, 430, 60));

        lblgender1.setText("Sex:");
        AddPatientTab.add(lblgender1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 270, 90, 30));

        tfSnameADDp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfSnameADDpActionPerformed(evt);
            }
        });
        AddPatientTab.add(tfSnameADDp, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 160, 230, 50));

        lbldIAGNOSIS.setText("Diagnosis:");
        AddPatientTab.add(lbldIAGNOSIS, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 510, 90, 30));

        tfSymptomsADDp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfSymptomsADDpActionPerformed(evt);
            }
        });
        AddPatientTab.add(tfSymptomsADDp, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 370, 430, 130));

        lblSymptoms.setText("Symptoms:");
        AddPatientTab.add(lblSymptoms, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 370, 90, 30));

        cbMedAidADDp.setText("Patient Possesses Medical Aid");
        cbMedAidADDp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbMedAidADDpActionPerformed(evt);
            }
        });
        AddPatientTab.add(cbMedAidADDp, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 320, 210, -1));

        cbGenderADDp.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Male", "Female" }));
        cbGenderADDp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbGenderADDpActionPerformed(evt);
            }
        });
        AddPatientTab.add(cbGenderADDp, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 270, 120, 30));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mediseek/pat/Doctor/INJUREDpatient.png"))); // NOI18N
        AddPatientTab.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 70, 280, 280));

        btnAddPatient.setText("Add Patient");
        AddPatientTab.add(btnAddPatient, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 530, 160, -1));

        lblTitle6.setFont(new java.awt.Font("Bookman Old Style", 1, 25)); // NOI18N
        lblTitle6.setForeground(new java.awt.Color(255, 255, 255));
        lblTitle6.setText("Add a Patient:");
        AddPatientTab.add(lblTitle6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 0, 310, 80));
        AddPatientTab.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 390, 180, -1));

        jLabel8.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jLabel8.setText("Patient ID:");
        AddPatientTab.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 390, 90, 30));

        jTabbedPane1.addTab("Add a Patient", AddPatientTab);

        ViewPatientsHistoryTab.setBackground(new java.awt.Color(102, 116, 141));
        ViewPatientsHistoryTab.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTitle3.setFont(new java.awt.Font("Bookman Old Style", 1, 25)); // NOI18N
        lblTitle3.setForeground(new java.awt.Color(255, 255, 255));
        lblTitle3.setText("View Patients History:");
        ViewPatientsHistoryTab.add(lblTitle3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 0, 310, 80));
        ViewPatientsHistoryTab.add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 120, 180, -1));

        jLabel9.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jLabel9.setText("Patient ID:");
        ViewPatientsHistoryTab.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 120, 90, 30));

        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { " " };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane3.setViewportView(jList1);

        ViewPatientsHistoryTab.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 190, 1160, 360));

        jButton1.setText("See History of Patient");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        ViewPatientsHistoryTab.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 110, 160, 40));

        jTabbedPane1.addTab("View Patient History", ViewPatientsHistoryTab);

        AddStaffTab.setBackground(new java.awt.Color(99, 158, 158));
        AddStaffTab.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tfPasswordADD1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfPasswordADD1ActionPerformed(evt);
            }
        });
        AddStaffTab.add(tfPasswordADD1, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 450, 170, 30));

        lblname8.setText("Staff ID Password: ");
        AddStaffTab.add(lblname8, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 450, 120, 30));

        lblsname4.setText("Surname:");
        AddStaffTab.add(lblsname4, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 180, 90, -1));

        tfQualADD1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfQualADD1ActionPerformed(evt);
            }
        });
        AddStaffTab.add(tfQualADD1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 490, 430, 70));

        lblJD4.setText("Specialty: ");
        AddStaffTab.add(lblJD4, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 330, 90, 30));

        tfSnameADD1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfSnameADD1ActionPerformed(evt);
            }
        });
        AddStaffTab.add(tfSnameADD1, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 170, 230, 50));

        lbldIAGNOSIS4.setText("Qualifications:");
        AddStaffTab.add(lbldIAGNOSIS4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 490, 90, 30));

        tfResidenceADD1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfResidenceADD1ActionPerformed(evt);
            }
        });
        AddStaffTab.add(tfResidenceADD1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 400, 430, 60));

        lblSymptoms4.setText("Residence:");
        AddStaffTab.add(lblSymptoms4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 400, 90, 30));

        cbGenderADD1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Male", "Female" }));
        cbGenderADD1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbGenderADD1ActionPerformed(evt);
            }
        });
        AddStaffTab.add(cbGenderADD1, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 290, 200, 30));

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mediseek/pat/Doctor/medicalstafficon.jpg"))); // NOI18N
        AddStaffTab.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 80, 260, 270));

        btnAddStaff1.setText("Update Your Information");
        AddStaffTab.add(btnAddStaff1, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 540, 220, -1));

        btnLOGOUT2.setText("LOGOUT");
        btnLOGOUT2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLOGOUT2ActionPerformed(evt);
            }
        });
        AddStaffTab.add(btnLOGOUT2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1090, -440, -1, -1));

        cbSpecialtyADD1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select a specialty:", "Administration", "General Practitioner", "Cardiologist", "Pharmacist", "Infectious Diseases Specialist", "Prosthetist", "Neurologist", "Gynaecologist", "Oncologist", " ", " " }));
        cbSpecialtyADD1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbSpecialtyADD1ActionPerformed(evt);
            }
        });
        AddStaffTab.add(cbSpecialtyADD1, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 330, 200, 30));

        lblgender6.setText("Sex:");
        AddStaffTab.add(lblgender6, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 290, 90, 30));

        lblJD5.setText("Job Description:");
        AddStaffTab.add(lblJD5, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 290, 90, 30));

        cbJobADD1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select a description", "Doctor", "Pharmacist", "Receptionist", "Administrator" }));
        AddStaffTab.add(cbJobADD1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 290, 200, 30));

        tfnameADD1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfnameADD1ActionPerformed(evt);
            }
        });
        AddStaffTab.add(tfnameADD1, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 80, 230, 50));

        jLabel15.setText("Personal Information");
        AddStaffTab.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 370, 130, 30));

        lblname9.setText("Name:");
        AddStaffTab.add(lblname9, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 90, 90, 30));

        lblname10.setText("Contact No:");
        AddStaffTab.add(lblname10, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 410, 90, 30));

        tfContactADD1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfContactADD1ActionPerformed(evt);
            }
        });
        AddStaffTab.add(tfContactADD1, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 410, 170, 30));

        lblTitle4.setFont(new java.awt.Font("Bookman Old Style", 1, 25)); // NOI18N
        lblTitle4.setForeground(new java.awt.Color(255, 255, 255));
        lblTitle4.setText("Your Personal Info:");
        AddStaffTab.add(lblTitle4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 0, 310, 80));

        jTabbedPane1.addTab("Personal Information", AddStaffTab);

        getContentPane().add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 1260, 640));

        btnLogout.setText("LOGOUT");
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });
        getContentPane().add(btnLogout, new org.netbeans.lib.awtextra.AbsoluteConstraints(1210, 10, -1, -1));

        lblTitle.setFont(new java.awt.Font("Bookman Old Style", 1, 36)); // NOI18N
        lblTitle.setForeground(new java.awt.Color(0, 153, 153));
        lblTitle.setText("Receptionist:");
        getContentPane().add(lblTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 0, 320, 80));

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\tendi\\OneDrive\\Education\\IT\\PAT\\Grade 12 PAT\\MediSeek_PAT\\MS Main1.jpg")); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1300, 770));

        jMenu5.setText("File");
        jMenuBar3.add(jMenu5);

        jMenu6.setText("Edit");
        jMenuBar3.add(jMenu6);

        setJMenuBar(jMenuBar3);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        LoginGUIoption LoginGUI = new LoginGUIoption();
        LoginGUI.setVisible(true);
        this.dispose();

    }//GEN-LAST:event_btnLogoutActionPerformed

    private void btnAddPatientPageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddPatientPageActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAddPatientPageActionPerformed

    private void btnShowPatient1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnShowPatient1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnShowPatient1ActionPerformed

    private void tfnameADDpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfnameADDpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfnameADDpActionPerformed

    private void tfDiagnosisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfDiagnosisActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfDiagnosisActionPerformed

    private void tfSnameADDpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfSnameADDpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfSnameADDpActionPerformed

    private void tfSymptomsADDpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfSymptomsADDpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfSymptomsADDpActionPerformed

    private void cbMedAidADDpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbMedAidADDpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbMedAidADDpActionPerformed

    private void cbGenderADDpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbGenderADDpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbGenderADDpActionPerformed

    private void tfPasswordADD1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfPasswordADD1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfPasswordADD1ActionPerformed

    private void tfQualADD1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfQualADD1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfQualADD1ActionPerformed

    private void tfSnameADD1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfSnameADD1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfSnameADD1ActionPerformed

    private void tfResidenceADD1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfResidenceADD1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfResidenceADD1ActionPerformed

    private void cbGenderADD1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbGenderADD1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbGenderADD1ActionPerformed

    private void btnLOGOUT2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLOGOUT2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnLOGOUT2ActionPerformed

    private void cbSpecialtyADD1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbSpecialtyADD1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbSpecialtyADD1ActionPerformed

    private void tfnameADD1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfnameADD1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfnameADD1ActionPerformed

    private void tfContactADD1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfContactADD1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfContactADD1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnAddAppActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddAppActionPerformed
       
         addAppointmentGUI LoginGUI = new addAppointmentGUI();
        LoginGUI.setVisible(true);
        
        
    }//GEN-LAST:event_btnAddAppActionPerformed

    private void btnAddApp1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddApp1ActionPerformed
      
          addAppointmentGUI LoginGUI = new addAppointmentGUI();
        LoginGUI.setVisible(true);
        
        
    }//GEN-LAST:event_btnAddApp1ActionPerformed

    private void tfPassword1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfPassword1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfPassword1ActionPerformed

    private void tfQual1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfQual1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfQual1ActionPerformed

    private void tfSname3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfSname3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfSname3ActionPerformed

    private void tfResidence1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfResidence1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfResidence1ActionPerformed

    private void cbGender1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbGender1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbGender1ActionPerformed

    private void btnLOGOUT1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLOGOUT1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnLOGOUT1ActionPerformed

    private void tfname4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfname4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfname4ActionPerformed

    private void tfContact1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfContact1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfContact1ActionPerformed

    private void tfStaffID1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfStaffID1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfStaffID1ActionPerformed

    private void cbSpecialtyOrder1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbSpecialtyOrder1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbSpecialtyOrder1ActionPerformed

    private void tfnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfnameActionPerformed

    private void tfDiagnosis2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfDiagnosis2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfDiagnosis2ActionPerformed

    private void tfSnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfSnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfSnameActionPerformed

    private void tfSymptomsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfSymptomsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfSymptomsActionPerformed

    private void jCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox1ActionPerformed

    private void cbSpecCodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbSpecCodeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbSpecCodeActionPerformed

    private void jComboBox3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ReceptionistPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ReceptionistPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ReceptionistPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ReceptionistPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ReceptionistPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel AddPatientTab;
    private javax.swing.JPanel AddStaffTab;
    private javax.swing.JPanel PatientInfoPanel;
    private javax.swing.JPanel PatientInfoPanel3;
    private javax.swing.JPanel ViewAppointmentsTab;
    private javax.swing.JPanel ViewPatientsHistoryTab;
    private javax.swing.JScrollPane ViewPatientsTab;
    private javax.swing.JPanel ViewStaffTab1;
    private javax.swing.JButton btnAddApp;
    private javax.swing.JButton btnAddApp1;
    private javax.swing.JButton btnAddPatient;
    private javax.swing.JButton btnAddPatientPage;
    private javax.swing.JButton btnAddStaff1;
    private javax.swing.JButton btnLOGOUT1;
    private javax.swing.JButton btnLOGOUT2;
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnShowPatient1;
    private javax.swing.JComboBox<String> cbGender1;
    private javax.swing.JComboBox<String> cbGenderADD1;
    private javax.swing.JComboBox<String> cbGenderADDp;
    private javax.swing.JComboBox<String> cbJob2;
    private javax.swing.JComboBox<String> cbJobADD1;
    private javax.swing.JCheckBox cbMedAidADDp;
    private javax.swing.JComboBox<String> cbSpecCode;
    private javax.swing.JComboBox<String> cbSpecialty1;
    private javax.swing.JComboBox<String> cbSpecialtyADD1;
    private javax.swing.JComboBox<String> cbSpecialtyOrder1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JComboBox<String> jComboBox5;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JList<String> jList1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuBar jMenuBar3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JLabel lblJD2;
    private javax.swing.JLabel lblJD3;
    private javax.swing.JLabel lblJD4;
    private javax.swing.JLabel lblJD5;
    private javax.swing.JLabel lblSymptoms;
    private javax.swing.JLabel lblSymptoms2;
    private javax.swing.JLabel lblSymptoms4;
    private javax.swing.JLabel lblSymptoms5;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblTitle1;
    private javax.swing.JLabel lblTitle2;
    private javax.swing.JLabel lblTitle3;
    private javax.swing.JLabel lblTitle4;
    private javax.swing.JLabel lblTitle6;
    private javax.swing.JLabel lblTitle7;
    private javax.swing.JLabel lblTitle8;
    private javax.swing.JLabel lblTitle9;
    private javax.swing.JLabel lbldIAGNOSIS;
    private javax.swing.JLabel lbldIAGNOSIS2;
    private javax.swing.JLabel lbldIAGNOSIS4;
    private javax.swing.JLabel lbldIAGNOSIS5;
    private javax.swing.JLabel lblgender1;
    private javax.swing.JLabel lblgender2;
    private javax.swing.JLabel lblgender3;
    private javax.swing.JLabel lblgender5;
    private javax.swing.JLabel lblgender6;
    private javax.swing.JLabel lblname;
    private javax.swing.JLabel lblname10;
    private javax.swing.JLabel lblname11;
    private javax.swing.JLabel lblname2;
    private javax.swing.JLabel lblname6;
    private javax.swing.JLabel lblname7;
    private javax.swing.JLabel lblname8;
    private javax.swing.JLabel lblname9;
    private javax.swing.JLabel lblsname;
    private javax.swing.JLabel lblsname2;
    private javax.swing.JLabel lblsname4;
    private javax.swing.JLabel lblsname5;
    private javax.swing.JList<String> lstAppoint;
    private javax.swing.JList<String> lstPatients;
    private javax.swing.JList<String> lstStaff1;
    private javax.swing.JTextField tfContact1;
    private javax.swing.JTextField tfContactADD1;
    private javax.swing.JTextField tfDiagnosis;
    private javax.swing.JTextField tfDiagnosis2;
    private javax.swing.JTextField tfPassword1;
    private javax.swing.JTextField tfPasswordADD1;
    private javax.swing.JTextField tfQual1;
    private javax.swing.JTextField tfQualADD1;
    private javax.swing.JTextField tfResidence1;
    private javax.swing.JTextField tfResidenceADD1;
    private javax.swing.JTextField tfSname;
    private javax.swing.JTextField tfSname3;
    private javax.swing.JTextField tfSnameADD1;
    private javax.swing.JTextField tfSnameADDp;
    private javax.swing.JTextField tfStaffID1;
    private javax.swing.JTextField tfSymptoms;
    private javax.swing.JTextField tfSymptomsADDp;
    private javax.swing.JTextField tf_fName1;
    private javax.swing.JTextField tf_sName;
    private javax.swing.JTextField tfname;
    private javax.swing.JTextField tfname4;
    private javax.swing.JTextField tfnameADD1;
    private javax.swing.JTextField tfnameADDp;
    // End of variables declaration//GEN-END:variables
}
