/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mediseek.pat.Pharmacist;

/**
 *
 * @author tendi
 */
public class PrescriptionGUI extends javax.swing.JFrame {

    /**
     * Creates new form PrescriptionGUI
     */
    public PrescriptionGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblTitle = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        tfPatient_ID = new javax.swing.JTextField();
        tf_Med2Cost = new javax.swing.JTextField();
        btnPrintBill = new javax.swing.JButton();
        tf_MedTotalCost = new javax.swing.JTextField();
        tf_Med3Cost = new javax.swing.JTextField();
        tf_Med4Cost = new javax.swing.JTextField();
        tf_Med1Cost = new javax.swing.JTextField();
        tf_PatientID4 = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        cbMed1 = new javax.swing.JComboBox<>();
        cbMed2 = new javax.swing.JComboBox<>();
        cbMed3 = new javax.swing.JComboBox<>();
        cbMed4 = new javax.swing.JComboBox<>();
        jspinMed4 = new javax.swing.JSpinner();
        jspinMed1 = new javax.swing.JSpinner();
        jspinMed2 = new javax.swing.JSpinner();
        jspinMed3 = new javax.swing.JSpinner();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 102, 102));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTitle.setFont(new java.awt.Font("Bookman Old Style", 1, 36)); // NOI18N
        lblTitle.setForeground(new java.awt.Color(102, 255, 204));
        lblTitle.setText("Issue a Prescription:");
        jPanel1.add(lblTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 390, 80));

        jLabel7.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jLabel7.setText("Qauntity:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 130, 70, 30));

        jLabel8.setFont(new java.awt.Font("sansserif", 0, 16)); // NOI18N
        jLabel8.setText("R");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 410, 20, 20));

        jLabel9.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jLabel9.setText("Medicines:");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 130, 90, 30));

        jLabel10.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jLabel10.setText("Cost:");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 130, 50, 30));

        jLabel11.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jLabel11.setText("1.");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, 20, 30));

        tfPatient_ID.setBackground(new java.awt.Color(23, 38, 63));
        jPanel1.add(tfPatient_ID, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 80, 180, -1));

        tf_Med2Cost.setBackground(new java.awt.Color(6, 23, 37));
        tf_Med2Cost.setForeground(new java.awt.Color(255, 255, 255));
        tf_Med2Cost.setToolTipText("Enter the ID of the patient you wish to schedule an appointment for. NOTE: They have to be added as a patient in the hospital database or you may not progress!!");
        jPanel1.add(tf_Med2Cost, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 240, 100, 40));

        btnPrintBill.setBackground(new java.awt.Color(0, 204, 51));
        btnPrintBill.setForeground(new java.awt.Color(0, 0, 0));
        btnPrintBill.setText("PRINT");
        btnPrintBill.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrintBillActionPerformed(evt);
            }
        });
        jPanel1.add(btnPrintBill, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 570, -1, -1));

        tf_MedTotalCost.setBackground(new java.awt.Color(6, 23, 37));
        tf_MedTotalCost.setForeground(new java.awt.Color(255, 255, 255));
        tf_MedTotalCost.setToolTipText("Enter the ID of the patient you wish to schedule an appointment for. NOTE: They have to be added as a patient in the hospital database or you may not progress!!");
        jPanel1.add(tf_MedTotalCost, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 480, 100, 40));

        tf_Med3Cost.setBackground(new java.awt.Color(6, 23, 37));
        tf_Med3Cost.setForeground(new java.awt.Color(255, 255, 255));
        tf_Med3Cost.setToolTipText("Enter the ID of the patient you wish to schedule an appointment for. NOTE: They have to be added as a patient in the hospital database or you may not progress!!");
        jPanel1.add(tf_Med3Cost, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 320, 100, 40));

        tf_Med4Cost.setBackground(new java.awt.Color(6, 23, 37));
        tf_Med4Cost.setForeground(new java.awt.Color(255, 255, 255));
        tf_Med4Cost.setToolTipText("Enter the ID of the patient you wish to schedule an appointment for. NOTE: They have to be added as a patient in the hospital database or you may not progress!!");
        jPanel1.add(tf_Med4Cost, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 400, 100, 40));

        tf_Med1Cost.setBackground(new java.awt.Color(6, 23, 37));
        tf_Med1Cost.setForeground(new java.awt.Color(255, 255, 255));
        tf_Med1Cost.setToolTipText("Enter the ID of the patient you wish to schedule an appointment for. NOTE: They have to be added as a patient in the hospital database or you may not progress!!");
        jPanel1.add(tf_Med1Cost, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 160, 100, 40));

        tf_PatientID4.setBackground(new java.awt.Color(6, 23, 37));
        tf_PatientID4.setForeground(new java.awt.Color(255, 255, 255));
        tf_PatientID4.setToolTipText("Enter the ID of the patient you wish to schedule an appointment for. NOTE: They have to be added as a patient in the hospital database or you may not progress!!");
        jPanel1.add(tf_PatientID4, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 160, 100, 40));

        jLabel12.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jLabel12.setText("2.");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, 20, 30));

        jLabel13.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jLabel13.setText("3.");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 320, 20, 30));

        jLabel14.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jLabel14.setText("4.");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 400, 20, 30));

        cbMed1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel1.add(cbMed1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 170, 110, -1));

        cbMed2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel1.add(cbMed2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 250, 110, -1));

        cbMed3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel1.add(cbMed3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 320, 110, -1));

        cbMed4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel1.add(cbMed4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 400, 110, -1));
        jPanel1.add(jspinMed4, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 400, -1, -1));
        jPanel1.add(jspinMed1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 170, -1, -1));
        jPanel1.add(jspinMed2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 250, -1, -1));
        jPanel1.add(jspinMed3, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 320, -1, -1));

        jLabel4.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jLabel4.setText("Patient ID:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 80, 90, 30));

        jLabel1.setText("********************************************************************************");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 520, 400, -1));

        jLabel2.setText("********************************************************************************");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(11, 450, 400, -1));

        jLabel3.setText("********************************************************************************");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 460, 400, -1));

        jLabel15.setFont(new java.awt.Font("sansserif", 1, 16)); // NOI18N
        jLabel15.setText("Total: R");
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 490, 60, 20));

        jLabel16.setFont(new java.awt.Font("sansserif", 0, 16)); // NOI18N
        jLabel16.setText("R");
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 169, 20, -1));

        jLabel17.setFont(new java.awt.Font("sansserif", 0, 16)); // NOI18N
        jLabel17.setText("R");
        jPanel1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 250, 20, 20));

        jLabel18.setFont(new java.awt.Font("sansserif", 0, 16)); // NOI18N
        jLabel18.setText("R");
        jPanel1.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 330, 20, 20));

        jButton1.setBackground(new java.awt.Color(102, 102, 102));
        jButton1.setText("CLOSE");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 570, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 420, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 420, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 610, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 610, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPrintBillActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrintBillActionPerformed
       
        
        
        
        
        

    }//GEN-LAST:event_btnPrintBillActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
     
        
        this.dispose();
        
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PrescriptionGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PrescriptionGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PrescriptionGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PrescriptionGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PrescriptionGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnPrintBill;
    private javax.swing.JComboBox<String> cbMed1;
    private javax.swing.JComboBox<String> cbMed2;
    private javax.swing.JComboBox<String> cbMed3;
    private javax.swing.JComboBox<String> cbMed4;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSpinner jspinMed1;
    private javax.swing.JSpinner jspinMed2;
    private javax.swing.JSpinner jspinMed3;
    private javax.swing.JSpinner jspinMed4;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JTextField tfPatient_ID;
    private javax.swing.JTextField tf_Med1Cost;
    private javax.swing.JTextField tf_Med2Cost;
    private javax.swing.JTextField tf_Med3Cost;
    private javax.swing.JTextField tf_Med4Cost;
    private javax.swing.JTextField tf_MedTotalCost;
    private javax.swing.JTextField tf_PatientID4;
    // End of variables declaration//GEN-END:variables
}
